version: "3"
services:
  musa-db:
    image: postgres:13
    container_name: musa-db-container
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: password
      POSTGRES_DB: musa
    ports:
      - 5432:5432
    volumes:
      - musa-db:/var/lib/postgresql/musa-db/
volumes:
  musa-db:
